version: '3'

services:

  runtime:
    platform: linux/amd64
    image: CloudRun-Base/runtime:dev
    environment:
      LOCAL_DEPLOYMENT: 'false'
      PORT: "${PORT:-8080}"
    build: ./backend/CloudRun-Base
    restart: unless-stopped
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "${PORT:-8080}"]
    networks:
      - app
    volumes:
      - ./backend/CloudRun-Base:/app
      - models_volume:/app/models
    working_dir: /app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"

networks:
  app:
    driver: bridge

volumes:
  models_volume: